name: Digiguru.co.uk
description: AI, technology, creativity and personal growth articles, experiments and presentations from Adam Hall.
highlighter: rouge
##safe: true
lsi: false
comments: false
url: "https://art.digiguru.co.uk"
plugins: 
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap
    ##- octopress-paginate
paginate: 5
paginate_path: "page-:num/"
future: true
theme: jekyll-theme-minimal
exclude:
    - presentation-source
    - scripts
